-- Auto-generated by scripts/parse-pricing-excel.py
-- Source: contex/BẢNG GIÁ ALPHA DIGITAL.xlsx
-- Stats: 1 categories, 3 products, 18 variants, 18 blog posts
-- Run: docker exec -i <db-container> psql -U adc_admin -d adc_marketing < prisma/seed-products-test.sql

BEGIN;

-- ========== Categories ==========
INSERT INTO product_categories (id, name_vi, slug, display_order, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'DỊCH VỤ GIA CÔNG', 'dich-vu-gia-cong', 1, true, NOW(), NOW()) ON CONFLICT (slug) DO NOTHING;

-- ========== Products ==========
INSERT INTO products (id, category_id, sku, name_vi, slug, description_vi, material, display_order, is_active, is_featured, seo_title, seo_description, created_at, updated_at) VALUES (gen_random_uuid(), (SELECT id FROM product_categories WHERE slug = 'dich-vu-gia-cong'), 'dvik11', 'Dịch vụ in kl 3D gia công CoCr', 'dich-vu-in-kl-3d-gia-cong-cocr', 'Dịch vụ bao gồm 8 biến thể:
- Sườn mão
- Sườn trên implant
- Thanh bar bán hám
- Thanh bar toàn hàm
- Thimble bán hàm
- Thimble toàn hàm
- ... và 2 biến thể khác

Liên hệ Alpha Digital Center để nhận báo giá chi tiết theo số lượng.', 'CoCr', 1, true, false, 'Dịch vụ in kl 3D gia công CoCr — Alpha Digital Center', 'Dịch vụ bao gồm 8 biến thể: - Sườn mão - Sườn trên implant - Thanh bar bán hám - Thanh bar toàn hàm - Thimble bán hàm - Thimble toàn hàm - ... và 2 biến thể khá', NOW(), NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (id, category_id, sku, name_vi, slug, description_vi, material, display_order, is_active, is_featured, seo_title, seo_description, created_at, updated_at) VALUES (gen_random_uuid(), (SELECT id FROM product_categories WHERE slug = 'dich-vu-gia-cong'), 'dvik21', 'Dịch vụ in kl 3D gia công Titan', 'dich-vu-in-kl-3d-gia-cong-titan', 'Dịch vụ bao gồm 8 biến thể:
- Sườn mão
- Sườn trên implant
- Thanh bar bán hám
- Thanh bar toàn hàm
- Thimble bán hàm
- Thimble toàn hàm
- ... và 2 biến thể khác

Liên hệ Alpha Digital Center để nhận báo giá chi tiết theo số lượng.', 'Titan', 2, true, false, 'Dịch vụ in kl 3D gia công Titan — Alpha Digital Center', 'Dịch vụ bao gồm 8 biến thể: - Sườn mão - Sườn trên implant - Thanh bar bán hám - Thanh bar toàn hàm - Thimble bán hàm - Thimble toàn hàm - ... và 2 biến thể khá', NOW(), NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (id, category_id, sku, name_vi, slug, description_vi, material, display_order, is_active, is_featured, seo_title, seo_description, created_at, updated_at) VALUES (gen_random_uuid(), (SELECT id FROM product_categories WHERE slug = 'dich-vu-gia-cong'), 'dvgt1', 'Dịch vụ gia công thêm in 3D Kim loại', 'dich-vu-gia-cong-them-in-3d-kim-loai', 'Dịch vụ bao gồm 2 biến thể:
- In rỗng
- Mill kết nối

Liên hệ Alpha Digital Center để nhận báo giá chi tiết theo số lượng.', NULL, 3, true, false, 'Dịch vụ gia công thêm in 3D Kim loại — Alpha Digital Center', 'Dịch vụ bao gồm 2 biến thể: - In rỗng - Mill kết nối  Liên hệ Alpha Digital Center để nhận báo giá chi tiết theo số lượng.', NOW(), NOW()) ON CONFLICT (slug) DO NOTHING;

-- ========== ProductVariants + BlogPosts (one post per variant) ==========
INSERT INTO product_variants (id, product_id, variant_name_vi, unit, price_vnd, price_note, is_active, created_at) VALUES (gen_random_uuid(), (SELECT id FROM products WHERE slug = 'dich-vu-in-kl-3d-gia-cong-cocr'), 'Sườn mão', 'Cái', 35000, 'Dịch vụ in kim loại bằng máy in 3D kim loại từ file khách hàng gửi. Sản phẩm in xong cắt ti giao ngay không hoàn thiện, không bảo hành. Nếu có xảy ra sai sót in hỏng thì in lại cho khách hàng.', true, NOW());
INSERT INTO blog_posts (id, title_vi, slug, excerpt_vi, content_vi, category, tags, status, published_at, seo_title, seo_description, view_count, ai_generated, created_at, updated_at) VALUES (gen_random_uuid(), 'Dịch vụ in kl 3D gia công CoCr — Sườn mão', 'dich-vu-in-kl-3d-gia-cong-cocr-suon-mao', 'Sườn mão thuộc dòng Dịch vụ in kl 3D gia công CoCr của Alpha Digital Center. Giá tham khảo: 35.000 VND/Cái.', '## Sườn mão — chi tiết dịch vụ

**Sườn mão** là một biến thể thuộc dòng sản phẩm/dịch vụ **Dịch vụ in kl 3D gia công CoCr** do Alpha Digital Center gia công. Biến thể này phù hợp với các yêu cầu gia công đặc thù trong phòng lab nha khoa hiện đại.

### Thông số kỹ thuật

- **Vật liệu:** CoCr
- **Đơn vị tính:** Cái
- **Giá tham khảo:** 35.000 VND / Cái

### Ghi chú từ nhà sản xuất

> Dịch vụ in kim loại bằng máy in 3D kim loại từ file khách hàng gửi. Sản phẩm in xong cắt ti giao ngay không hoàn thiện, không bảo hành. Nếu có xảy ra sai sót in hỏng thì in lại cho khách hàng.

### Quy trình gia công tại Alpha Digital Center

Mỗi biến thể gia công tại ADC đều trải qua quy trình khép kín, đảm bảo chất lượng ổn định và thời gian giao đúng hẹn:

1. **Tiếp nhận file & kiểm tra** — đội QC kiểm tra file CAD/CAM do labo gửi về, báo cáo sai sót nếu có.
2. **Thiết kế/điều chỉnh** (nếu thuê) — các chuyên viên thiết kế của ADC hiệu chỉnh theo vật liệu và yêu cầu lâm sàng.
3. **Gia công chính xác** — hệ thống máy CNC 5 trục, in 3D kim loại SLM, scanner E4 đảm bảo dung sai tối thiểu.
4. **QC xuất xưởng** — 5 vòng kiểm tra trước khi đóng gói, kèm phiếu gia công ghi rõ lô vật liệu.

### Ứng dụng lâm sàng

Sườn mão thường được chỉ định cho các case phục hình có yêu cầu độ chính xác cao và tính thẩm mỹ tự nhiên. Labo đối tác của Alpha Digital Center có thể đặt số lượng lớn với lead time ổn định.

### Liên hệ đặt hàng

Xem thêm các biến thể khác trong dòng [Dịch vụ in kl 3D gia công CoCr](/san-pham/dich-vu-in-kl-3d-gia-cong-cocr) hoặc [liên hệ trực tiếp](/lien-he) để nhận báo giá chi tiết cho số lượng lớn và lịch giao hàng.', 'san-pham', ARRAY['CoCr','Sườn mão']::text[], 'published', NOW(), 'Dịch vụ in kl 3D gia công CoCr — Sườn mão | Giá 35.000 VND — Alpha Digital Center', 'Sườn mão thuộc dòng Dịch vụ in kl 3D gia công CoCr của Alpha Digital Center. Giá tham khảo: 35.000 VND/Cái. Bảo hành minh bạch, giao hàng đúng hẹn từ ADC.', 0, false, NOW(), NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO product_variants (id, product_id, variant_name_vi, unit, price_vnd, price_note, is_active, created_at) VALUES (gen_random_uuid(), (SELECT id FROM products WHERE slug = 'dich-vu-in-kl-3d-gia-cong-cocr'), 'Sườn trên implant', 'Cái', 50000, NULL, true, NOW());
INSERT INTO blog_posts (id, title_vi, slug, excerpt_vi, content_vi, category, tags, status, published_at, seo_title, seo_description, view_count, ai_generated, created_at, updated_at) VALUES (gen_random_uuid(), 'Dịch vụ in kl 3D gia công CoCr — Sườn trên implant', 'dich-vu-in-kl-3d-gia-cong-cocr-suon-tren-implant', 'Sườn trên implant thuộc dòng Dịch vụ in kl 3D gia công CoCr của Alpha Digital Center. Giá tham khảo: 50.000 VND/Cái.', '## Sườn trên implant — chi tiết dịch vụ

**Sườn trên implant** là một biến thể thuộc dòng sản phẩm/dịch vụ **Dịch vụ in kl 3D gia công CoCr** do Alpha Digital Center gia công. Biến thể này phù hợp với các yêu cầu gia công đặc thù trong phòng lab nha khoa hiện đại.

### Thông số kỹ thuật

- **Vật liệu:** CoCr
- **Đơn vị tính:** Cái
- **Giá tham khảo:** 50.000 VND / Cái

### Quy trình gia công tại Alpha Digital Center

Mỗi biến thể gia công tại ADC đều trải qua quy trình khép kín, đảm bảo chất lượng ổn định và thời gian giao đúng hẹn:

1. **Tiếp nhận file & kiểm tra** — đội QC kiểm tra file CAD/CAM do labo gửi về, báo cáo sai sót nếu có.
2. **Thiết kế/điều chỉnh** (nếu thuê) — các chuyên viên thiết kế của ADC hiệu chỉnh theo vật liệu và yêu cầu lâm sàng.
3. **Gia công chính xác** — hệ thống máy CNC 5 trục, in 3D kim loại SLM, scanner E4 đảm bảo dung sai tối thiểu.
4. **QC xuất xưởng** — 5 vòng kiểm tra trước khi đóng gói, kèm phiếu gia công ghi rõ lô vật liệu.

### Ứng dụng lâm sàng

Sườn trên implant thường được chỉ định cho các case phục hình có yêu cầu độ chính xác cao và tính thẩm mỹ tự nhiên. Labo đối tác của Alpha Digital Center có thể đặt số lượng lớn với lead time ổn định.

### Liên hệ đặt hàng

Xem thêm các biến thể khác trong dòng [Dịch vụ in kl 3D gia công CoCr](/san-pham/dich-vu-in-kl-3d-gia-cong-cocr) hoặc [liên hệ trực tiếp](/lien-he) để nhận báo giá chi tiết cho số lượng lớn và lịch giao hàng.', 'san-pham', ARRAY['CoCr','Sườn trên implant']::text[], 'published', NOW(), 'Dịch vụ in kl 3D gia công CoCr — Sườn trên implant | Giá 50.000 VND — Alpha Digital Center', 'Sườn trên implant thuộc dòng Dịch vụ in kl 3D gia công CoCr của Alpha Digital Center. Giá tham khảo: 50.000 VND/Cái. Bảo hành minh bạch, giao hàng đúng hẹn từ A', 0, false, NOW(), NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO product_variants (id, product_id, variant_name_vi, unit, price_vnd, price_note, is_active, created_at) VALUES (gen_random_uuid(), (SELECT id FROM products WHERE slug = 'dich-vu-in-kl-3d-gia-cong-cocr'), 'Thanh bar bán hám', 'Cái', 600000, NULL, true, NOW());
INSERT INTO blog_posts (id, title_vi, slug, excerpt_vi, content_vi, category, tags, status, published_at, seo_title, seo_description, view_count, ai_generated, created_at, updated_at) VALUES (gen_random_uuid(), 'Dịch vụ in kl 3D gia công CoCr — Thanh bar bán hám', 'dich-vu-in-kl-3d-gia-cong-cocr-thanh-bar-ban-ham', 'Thanh bar bán hám thuộc dòng Dịch vụ in kl 3D gia công CoCr của Alpha Digital Center. Giá tham khảo: 600.000 VND/Cái.', '## Thanh bar bán hám — chi tiết dịch vụ

**Thanh bar bán hám** là một biến thể thuộc dòng sản phẩm/dịch vụ **Dịch vụ in kl 3D gia công CoCr** do Alpha Digital Center gia công. Biến thể này phù hợp với các yêu cầu gia công đặc thù trong phòng lab nha khoa hiện đại.

### Thông số kỹ thuật

- **Vật liệu:** CoCr
- **Đơn vị tính:** Cái
- **Giá tham khảo:** 600.000 VND / Cái

### Quy trình gia công tại Alpha Digital Center

Mỗi biến thể gia công tại ADC đều trải qua quy trình khép kín, đảm bảo chất lượng ổn định và thời gian giao đúng hẹn:

1. **Tiếp nhận file & kiểm tra** — đội QC kiểm tra file CAD/CAM do labo gửi về, báo cáo sai sót nếu có.
2. **Thiết kế/điều chỉnh** (nếu thuê) — các chuyên viên thiết kế của ADC hiệu chỉnh theo vật liệu và yêu cầu lâm sàng.
3. **Gia công chính xác** — hệ thống máy CNC 5 trục, in 3D kim loại SLM, scanner E4 đảm bảo dung sai tối thiểu.
4. **QC xuất xưởng** — 5 vòng kiểm tra trước khi đóng gói, kèm phiếu gia công ghi rõ lô vật liệu.

### Ứng dụng lâm sàng

Thanh bar bán hám thường được chỉ định cho các case phục hình có yêu cầu độ chính xác cao và tính thẩm mỹ tự nhiên. Labo đối tác của Alpha Digital Center có thể đặt số lượng lớn với lead time ổn định.

### Liên hệ đặt hàng

Xem thêm các biến thể khác trong dòng [Dịch vụ in kl 3D gia công CoCr](/san-pham/dich-vu-in-kl-3d-gia-cong-cocr) hoặc [liên hệ trực tiếp](/lien-he) để nhận báo giá chi tiết cho số lượng lớn và lịch giao hàng.', 'san-pham', ARRAY['CoCr','Thanh bar bán hám']::text[], 'published', NOW(), 'Dịch vụ in kl 3D gia công CoCr — Thanh bar bán hám | Giá 600.000 VND — Alpha Digital Center', 'Thanh bar bán hám thuộc dòng Dịch vụ in kl 3D gia công CoCr của Alpha Digital Center. Giá tham khảo: 600.000 VND/Cái. Bảo hành minh bạch, giao hàng đúng hẹn từ', 0, false, NOW(), NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO product_variants (id, product_id, variant_name_vi, unit, price_vnd, price_note, is_active, created_at) VALUES (gen_random_uuid(), (SELECT id FROM products WHERE slug = 'dich-vu-in-kl-3d-gia-cong-cocr'), 'Thanh bar toàn hàm', 'Cái', 800000, NULL, true, NOW());
INSERT INTO blog_posts (id, title_vi, slug, excerpt_vi, content_vi, category, tags, status, published_at, seo_title, seo_description, view_count, ai_generated, created_at, updated_at) VALUES (gen_random_uuid(), 'Dịch vụ in kl 3D gia công CoCr — Thanh bar toàn hàm', 'dich-vu-in-kl-3d-gia-cong-cocr-thanh-bar-toan-ham', 'Thanh bar toàn hàm thuộc dòng Dịch vụ in kl 3D gia công CoCr của Alpha Digital Center. Giá tham khảo: 800.000 VND/Cái.', '## Thanh bar toàn hàm — chi tiết dịch vụ

**Thanh bar toàn hàm** là một biến thể thuộc dòng sản phẩm/dịch vụ **Dịch vụ in kl 3D gia công CoCr** do Alpha Digital Center gia công. Biến thể này phù hợp với các yêu cầu gia công đặc thù trong phòng lab nha khoa hiện đại.

### Thông số kỹ thuật

- **Vật liệu:** CoCr
- **Đơn vị tính:** Cái
- **Giá tham khảo:** 800.000 VND / Cái

### Quy trình gia công tại Alpha Digital Center

Mỗi biến thể gia công tại ADC đều trải qua quy trình khép kín, đảm bảo chất lượng ổn định và thời gian giao đúng hẹn:

1. **Tiếp nhận file & kiểm tra** — đội QC kiểm tra file CAD/CAM do labo gửi về, báo cáo sai sót nếu có.
2. **Thiết kế/điều chỉnh** (nếu thuê) — các chuyên viên thiết kế của ADC hiệu chỉnh theo vật liệu và yêu cầu lâm sàng.
3. **Gia công chính xác** — hệ thống máy CNC 5 trục, in 3D kim loại SLM, scanner E4 đảm bảo dung sai tối thiểu.
4. **QC xuất xưởng** — 5 vòng kiểm tra trước khi đóng gói, kèm phiếu gia công ghi rõ lô vật liệu.

### Ứng dụng lâm sàng

Thanh bar toàn hàm thường được chỉ định cho các case phục hình có yêu cầu độ chính xác cao và tính thẩm mỹ tự nhiên. Labo đối tác của Alpha Digital Center có thể đặt số lượng lớn với lead time ổn định.

### Liên hệ đặt hàng

Xem thêm các biến thể khác trong dòng [Dịch vụ in kl 3D gia công CoCr](/san-pham/dich-vu-in-kl-3d-gia-cong-cocr) hoặc [liên hệ trực tiếp](/lien-he) để nhận báo giá chi tiết cho số lượng lớn và lịch giao hàng.', 'san-pham', ARRAY['CoCr','Thanh bar toàn hàm']::text[], 'published', NOW(), 'Dịch vụ in kl 3D gia công CoCr — Thanh bar toàn hàm | Giá 800.000 VND — Alpha Digital Center', 'Thanh bar toàn hàm thuộc dòng Dịch vụ in kl 3D gia công CoCr của Alpha Digital Center. Giá tham khảo: 800.000 VND/Cái. Bảo hành minh bạch, giao hàng đúng hẹn từ', 0, false, NOW(), NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO product_variants (id, product_id, variant_name_vi, unit, price_vnd, price_note, is_active, created_at) VALUES (gen_random_uuid(), (SELECT id FROM products WHERE slug = 'dich-vu-in-kl-3d-gia-cong-cocr'), 'Thimble bán hàm', 'Cái', 800000, NULL, true, NOW());
INSERT INTO blog_posts (id, title_vi, slug, excerpt_vi, content_vi, category, tags, status, published_at, seo_title, seo_description, view_count, ai_generated, created_at, updated_at) VALUES (gen_random_uuid(), 'Dịch vụ in kl 3D gia công CoCr — Thimble bán hàm', 'dich-vu-in-kl-3d-gia-cong-cocr-thimble-ban-ham', 'Thimble bán hàm thuộc dòng Dịch vụ in kl 3D gia công CoCr của Alpha Digital Center. Giá tham khảo: 800.000 VND/Cái.', '## Thimble bán hàm — chi tiết dịch vụ

**Thimble bán hàm** là một biến thể thuộc dòng sản phẩm/dịch vụ **Dịch vụ in kl 3D gia công CoCr** do Alpha Digital Center gia công. Biến thể này phù hợp với các yêu cầu gia công đặc thù trong phòng lab nha khoa hiện đại.

### Thông số kỹ thuật

- **Vật liệu:** CoCr
- **Đơn vị tính:** Cái
- **Giá tham khảo:** 800.000 VND / Cái

### Quy trình gia công tại Alpha Digital Center

Mỗi biến thể gia công tại ADC đều trải qua quy trình khép kín, đảm bảo chất lượng ổn định và thời gian giao đúng hẹn:

1. **Tiếp nhận file & kiểm tra** — đội QC kiểm tra file CAD/CAM do labo gửi về, báo cáo sai sót nếu có.
2. **Thiết kế/điều chỉnh** (nếu thuê) — các chuyên viên thiết kế của ADC hiệu chỉnh theo vật liệu và yêu cầu lâm sàng.
3. **Gia công chính xác** — hệ thống máy CNC 5 trục, in 3D kim loại SLM, scanner E4 đảm bảo dung sai tối thiểu.
4. **QC xuất xưởng** — 5 vòng kiểm tra trước khi đóng gói, kèm phiếu gia công ghi rõ lô vật liệu.

### Ứng dụng lâm sàng

Thimble bán hàm thường được chỉ định cho các case phục hình có yêu cầu độ chính xác cao và tính thẩm mỹ tự nhiên. Labo đối tác của Alpha Digital Center có thể đặt số lượng lớn với lead time ổn định.

### Liên hệ đặt hàng

Xem thêm các biến thể khác trong dòng [Dịch vụ in kl 3D gia công CoCr](/san-pham/dich-vu-in-kl-3d-gia-cong-cocr) hoặc [liên hệ trực tiếp](/lien-he) để nhận báo giá chi tiết cho số lượng lớn và lịch giao hàng.', 'san-pham', ARRAY['CoCr','Thimble bán hàm']::text[], 'published', NOW(), 'Dịch vụ in kl 3D gia công CoCr — Thimble bán hàm | Giá 800.000 VND — Alpha Digital Center', 'Thimble bán hàm thuộc dòng Dịch vụ in kl 3D gia công CoCr của Alpha Digital Center. Giá tham khảo: 800.000 VND/Cái. Bảo hành minh bạch, giao hàng đúng hẹn từ AD', 0, false, NOW(), NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO product_variants (id, product_id, variant_name_vi, unit, price_vnd, price_note, is_active, created_at) VALUES (gen_random_uuid(), (SELECT id FROM products WHERE slug = 'dich-vu-in-kl-3d-gia-cong-cocr'), 'Thimble toàn hàm', 'Cái', 1200000, NULL, true, NOW());
INSERT INTO blog_posts (id, title_vi, slug, excerpt_vi, content_vi, category, tags, status, published_at, seo_title, seo_description, view_count, ai_generated, created_at, updated_at) VALUES (gen_random_uuid(), 'Dịch vụ in kl 3D gia công CoCr — Thimble toàn hàm', 'dich-vu-in-kl-3d-gia-cong-cocr-thimble-toan-ham', 'Thimble toàn hàm thuộc dòng Dịch vụ in kl 3D gia công CoCr của Alpha Digital Center. Giá tham khảo: 1.200.000 VND/Cái.', '## Thimble toàn hàm — chi tiết dịch vụ

**Thimble toàn hàm** là một biến thể thuộc dòng sản phẩm/dịch vụ **Dịch vụ in kl 3D gia công CoCr** do Alpha Digital Center gia công. Biến thể này phù hợp với các yêu cầu gia công đặc thù trong phòng lab nha khoa hiện đại.

### Thông số kỹ thuật

- **Vật liệu:** CoCr
- **Đơn vị tính:** Cái
- **Giá tham khảo:** 1.200.000 VND / Cái

### Quy trình gia công tại Alpha Digital Center

Mỗi biến thể gia công tại ADC đều trải qua quy trình khép kín, đảm bảo chất lượng ổn định và thời gian giao đúng hẹn:

1. **Tiếp nhận file & kiểm tra** — đội QC kiểm tra file CAD/CAM do labo gửi về, báo cáo sai sót nếu có.
2. **Thiết kế/điều chỉnh** (nếu thuê) — các chuyên viên thiết kế của ADC hiệu chỉnh theo vật liệu và yêu cầu lâm sàng.
3. **Gia công chính xác** — hệ thống máy CNC 5 trục, in 3D kim loại SLM, scanner E4 đảm bảo dung sai tối thiểu.
4. **QC xuất xưởng** — 5 vòng kiểm tra trước khi đóng gói, kèm phiếu gia công ghi rõ lô vật liệu.

### Ứng dụng lâm sàng

Thimble toàn hàm thường được chỉ định cho các case phục hình có yêu cầu độ chính xác cao và tính thẩm mỹ tự nhiên. Labo đối tác của Alpha Digital Center có thể đặt số lượng lớn với lead time ổn định.

### Liên hệ đặt hàng

Xem thêm các biến thể khác trong dòng [Dịch vụ in kl 3D gia công CoCr](/san-pham/dich-vu-in-kl-3d-gia-cong-cocr) hoặc [liên hệ trực tiếp](/lien-he) để nhận báo giá chi tiết cho số lượng lớn và lịch giao hàng.', 'san-pham', ARRAY['CoCr','Thimble toàn hàm']::text[], 'published', NOW(), 'Dịch vụ in kl 3D gia công CoCr — Thimble toàn hàm | Giá 1.200.000 VND — Alpha Digital Center', 'Thimble toàn hàm thuộc dòng Dịch vụ in kl 3D gia công CoCr của Alpha Digital Center. Giá tham khảo: 1.200.000 VND/Cái. Bảo hành minh bạch, giao hàng đúng hẹn từ', 0, false, NOW(), NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO product_variants (id, product_id, variant_name_vi, unit, price_vnd, price_note, is_active, created_at) VALUES (gen_random_uuid(), (SELECT id FROM products WHERE slug = 'dich-vu-in-kl-3d-gia-cong-cocr'), 'Máng HDPT', 'Cái', 2000000, NULL, true, NOW());
INSERT INTO blog_posts (id, title_vi, slug, excerpt_vi, content_vi, category, tags, status, published_at, seo_title, seo_description, view_count, ai_generated, created_at, updated_at) VALUES (gen_random_uuid(), 'Dịch vụ in kl 3D gia công CoCr — Máng HDPT', 'dich-vu-in-kl-3d-gia-cong-cocr-mang-hdpt', 'Máng HDPT thuộc dòng Dịch vụ in kl 3D gia công CoCr của Alpha Digital Center. Giá tham khảo: 2.000.000 VND/Cái.', '## Máng HDPT — chi tiết dịch vụ

**Máng HDPT** là một biến thể thuộc dòng sản phẩm/dịch vụ **Dịch vụ in kl 3D gia công CoCr** do Alpha Digital Center gia công. Biến thể này phù hợp với các yêu cầu gia công đặc thù trong phòng lab nha khoa hiện đại.

### Thông số kỹ thuật

- **Vật liệu:** CoCr
- **Đơn vị tính:** Cái
- **Giá tham khảo:** 2.000.000 VND / Cái

### Quy trình gia công tại Alpha Digital Center

Mỗi biến thể gia công tại ADC đều trải qua quy trình khép kín, đảm bảo chất lượng ổn định và thời gian giao đúng hẹn:

1. **Tiếp nhận file & kiểm tra** — đội QC kiểm tra file CAD/CAM do labo gửi về, báo cáo sai sót nếu có.
2. **Thiết kế/điều chỉnh** (nếu thuê) — các chuyên viên thiết kế của ADC hiệu chỉnh theo vật liệu và yêu cầu lâm sàng.
3. **Gia công chính xác** — hệ thống máy CNC 5 trục, in 3D kim loại SLM, scanner E4 đảm bảo dung sai tối thiểu.
4. **QC xuất xưởng** — 5 vòng kiểm tra trước khi đóng gói, kèm phiếu gia công ghi rõ lô vật liệu.

### Ứng dụng lâm sàng

Máng HDPT thường được chỉ định cho các case phục hình có yêu cầu độ chính xác cao và tính thẩm mỹ tự nhiên. Labo đối tác của Alpha Digital Center có thể đặt số lượng lớn với lead time ổn định.

### Liên hệ đặt hàng

Xem thêm các biến thể khác trong dòng [Dịch vụ in kl 3D gia công CoCr](/san-pham/dich-vu-in-kl-3d-gia-cong-cocr) hoặc [liên hệ trực tiếp](/lien-he) để nhận báo giá chi tiết cho số lượng lớn và lịch giao hàng.', 'san-pham', ARRAY['CoCr','Máng HDPT']::text[], 'published', NOW(), 'Dịch vụ in kl 3D gia công CoCr — Máng HDPT | Giá 2.000.000 VND — Alpha Digital Center', 'Máng HDPT thuộc dòng Dịch vụ in kl 3D gia công CoCr của Alpha Digital Center. Giá tham khảo: 2.000.000 VND/Cái. Bảo hành minh bạch, giao hàng đúng hẹn từ ADC.', 0, false, NOW(), NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO product_variants (id, product_id, variant_name_vi, unit, price_vnd, price_note, is_active, created_at) VALUES (gen_random_uuid(), (SELECT id FROM products WHERE slug = 'dich-vu-in-kl-3d-gia-cong-cocr'), 'Hàm khung', 'Cái', 300000, NULL, true, NOW());
INSERT INTO blog_posts (id, title_vi, slug, excerpt_vi, content_vi, category, tags, status, published_at, seo_title, seo_description, view_count, ai_generated, created_at, updated_at) VALUES (gen_random_uuid(), 'Dịch vụ in kl 3D gia công CoCr — Hàm khung', 'dich-vu-in-kl-3d-gia-cong-cocr-ham-khung', 'Hàm khung thuộc dòng Dịch vụ in kl 3D gia công CoCr của Alpha Digital Center. Giá tham khảo: 300.000 VND/Cái.', '## Hàm khung — chi tiết dịch vụ

**Hàm khung** là một biến thể thuộc dòng sản phẩm/dịch vụ **Dịch vụ in kl 3D gia công CoCr** do Alpha Digital Center gia công. Biến thể này phù hợp với các yêu cầu gia công đặc thù trong phòng lab nha khoa hiện đại.

### Thông số kỹ thuật

- **Vật liệu:** CoCr
- **Đơn vị tính:** Cái
- **Giá tham khảo:** 300.000 VND / Cái

### Quy trình gia công tại Alpha Digital Center

Mỗi biến thể gia công tại ADC đều trải qua quy trình khép kín, đảm bảo chất lượng ổn định và thời gian giao đúng hẹn:

1. **Tiếp nhận file & kiểm tra** — đội QC kiểm tra file CAD/CAM do labo gửi về, báo cáo sai sót nếu có.
2. **Thiết kế/điều chỉnh** (nếu thuê) — các chuyên viên thiết kế của ADC hiệu chỉnh theo vật liệu và yêu cầu lâm sàng.
3. **Gia công chính xác** — hệ thống máy CNC 5 trục, in 3D kim loại SLM, scanner E4 đảm bảo dung sai tối thiểu.
4. **QC xuất xưởng** — 5 vòng kiểm tra trước khi đóng gói, kèm phiếu gia công ghi rõ lô vật liệu.

### Ứng dụng lâm sàng

Hàm khung thường được chỉ định cho các case phục hình có yêu cầu độ chính xác cao và tính thẩm mỹ tự nhiên. Labo đối tác của Alpha Digital Center có thể đặt số lượng lớn với lead time ổn định.

### Liên hệ đặt hàng

Xem thêm các biến thể khác trong dòng [Dịch vụ in kl 3D gia công CoCr](/san-pham/dich-vu-in-kl-3d-gia-cong-cocr) hoặc [liên hệ trực tiếp](/lien-he) để nhận báo giá chi tiết cho số lượng lớn và lịch giao hàng.', 'san-pham', ARRAY['CoCr','Hàm khung']::text[], 'published', NOW(), 'Dịch vụ in kl 3D gia công CoCr — Hàm khung | Giá 300.000 VND — Alpha Digital Center', 'Hàm khung thuộc dòng Dịch vụ in kl 3D gia công CoCr của Alpha Digital Center. Giá tham khảo: 300.000 VND/Cái. Bảo hành minh bạch, giao hàng đúng hẹn từ ADC.', 0, false, NOW(), NOW()) ON CONFLICT (slug) DO NOTHING;

INSERT INTO product_variants (id, product_id, variant_name_vi, unit, price_vnd, price_note, is_active, created_at) VALUES (gen_random_uuid(), (SELECT id FROM products WHERE slug = 'dich-vu-in-kl-3d-gia-cong-titan'), 'Sườn mão', 'Cái', 70000, NULL, true, NOW());
INSERT INTO blog_posts (id, title_vi, slug, excerpt_vi, content_vi, category, tags, status, published_at, seo_title, seo_description, view_count, ai_generated, created_at, updated_at) VALUES (gen_random_uuid(), 'Dịch vụ in kl 3D gia công Titan — Sườn mão', 'dich-vu-in-kl-3d-gia-cong-titan-suon-mao', 'Sườn mão thuộc dòng Dịch vụ in kl 3D gia công Titan của Alpha Digital Center. Giá tham khảo: 70.000 VND/Cái.', '## Sườn mão — chi tiết dịch vụ

**Sườn mão** là một biến thể thuộc dòng sản phẩm/dịch vụ **Dịch vụ in kl 3D gia công Titan** do Alpha Digital Center gia công. Biến thể này phù hợp với các yêu cầu gia công đặc thù trong phòng lab nha khoa hiện đại.

### Thông số kỹ thuật

- **Vật liệu:** Titan
- **Đơn vị tính:** Cái
- **Giá tham khảo:** 70.000 VND / Cái

### Quy trình gia công tại Alpha Digital Center

Mỗi biến thể gia công tại ADC đều trải qua quy trình khép kín, đảm bảo chất lượng ổn định và thời gian giao đúng hẹn:

1. **Tiếp nhận file & kiểm tra** — đội QC kiểm tra file CAD/CAM do labo gửi về, báo cáo sai sót nếu có.
2. **Thiết kế/điều chỉnh** (nếu thuê) — các chuyên viên thiết kế của ADC hiệu chỉnh theo vật liệu và yêu cầu lâm sàng.
3. **Gia công chính xác** — hệ thống máy CNC 5 trục, in 3D kim loại SLM, scanner E4 đảm bảo dung sai tối thiểu.
4. **QC xuất xưởng** — 5 vòng kiểm tra trước khi đóng gói, kèm phiếu gia công ghi rõ lô vật liệu.

### Ứng dụng lâm sàng

Sườn mão thường được chỉ định cho các case phục hình có yêu cầu độ chính xác cao và tính thẩm mỹ tự nhiên. Labo đối tác của Alpha Digital Center có thể đặt số lượng lớn với lead time ổn định.

### Liên hệ đặt hàng

Xem thêm các biến thể khác trong dòng [Dịch vụ in kl 3D gia công Titan](/san-pham/dich-vu-in-kl-3d-gia-cong-titan) hoặc [liên hệ trực tiếp](/lien-he) để nhận báo giá chi tiết cho số lượng lớn và lịch giao hàng.', 'san-pham', ARRAY['Titan','Sườn mão']::text[], 'published', NOW(), 'Dịch vụ in kl 3D gia công Titan — Sườn mão | Giá 70.000 VND — Alpha Digital Center', 'Sườn mão thuộc dòng Dịch vụ in kl 3D gia công Titan của Alpha Digital Center. Giá tham khảo: 70.000 VND/Cái. Bảo hành minh bạch, giao hàng đúng hẹn từ ADC.', 0, false, NOW(), NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO product_variants (id, product_id, variant_name_vi, unit, price_vnd, price_note, is_active, created_at) VALUES (gen_random_uuid(), (SELECT id FROM products WHERE slug = 'dich-vu-in-kl-3d-gia-cong-titan'), 'Sườn trên implant', 'Cái', 100000, NULL, true, NOW());
INSERT INTO blog_posts (id, title_vi, slug, excerpt_vi, content_vi, category, tags, status, published_at, seo_title, seo_description, view_count, ai_generated, created_at, updated_at) VALUES (gen_random_uuid(), 'Dịch vụ in kl 3D gia công Titan — Sườn trên implant', 'dich-vu-in-kl-3d-gia-cong-titan-suon-tren-implant', 'Sườn trên implant thuộc dòng Dịch vụ in kl 3D gia công Titan của Alpha Digital Center. Giá tham khảo: 100.000 VND/Cái.', '## Sườn trên implant — chi tiết dịch vụ

**Sườn trên implant** là một biến thể thuộc dòng sản phẩm/dịch vụ **Dịch vụ in kl 3D gia công Titan** do Alpha Digital Center gia công. Biến thể này phù hợp với các yêu cầu gia công đặc thù trong phòng lab nha khoa hiện đại.

### Thông số kỹ thuật

- **Vật liệu:** Titan
- **Đơn vị tính:** Cái
- **Giá tham khảo:** 100.000 VND / Cái

### Quy trình gia công tại Alpha Digital Center

Mỗi biến thể gia công tại ADC đều trải qua quy trình khép kín, đảm bảo chất lượng ổn định và thời gian giao đúng hẹn:

1. **Tiếp nhận file & kiểm tra** — đội QC kiểm tra file CAD/CAM do labo gửi về, báo cáo sai sót nếu có.
2. **Thiết kế/điều chỉnh** (nếu thuê) — các chuyên viên thiết kế của ADC hiệu chỉnh theo vật liệu và yêu cầu lâm sàng.
3. **Gia công chính xác** — hệ thống máy CNC 5 trục, in 3D kim loại SLM, scanner E4 đảm bảo dung sai tối thiểu.
4. **QC xuất xưởng** — 5 vòng kiểm tra trước khi đóng gói, kèm phiếu gia công ghi rõ lô vật liệu.

### Ứng dụng lâm sàng

Sườn trên implant thường được chỉ định cho các case phục hình có yêu cầu độ chính xác cao và tính thẩm mỹ tự nhiên. Labo đối tác của Alpha Digital Center có thể đặt số lượng lớn với lead time ổn định.

### Liên hệ đặt hàng

Xem thêm các biến thể khác trong dòng [Dịch vụ in kl 3D gia công Titan](/san-pham/dich-vu-in-kl-3d-gia-cong-titan) hoặc [liên hệ trực tiếp](/lien-he) để nhận báo giá chi tiết cho số lượng lớn và lịch giao hàng.', 'san-pham', ARRAY['Titan','Sườn trên implant']::text[], 'published', NOW(), 'Dịch vụ in kl 3D gia công Titan — Sườn trên implant | Giá 100.000 VND — Alpha Digital Center', 'Sườn trên implant thuộc dòng Dịch vụ in kl 3D gia công Titan của Alpha Digital Center. Giá tham khảo: 100.000 VND/Cái. Bảo hành minh bạch, giao hàng đúng hẹn từ', 0, false, NOW(), NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO product_variants (id, product_id, variant_name_vi, unit, price_vnd, price_note, is_active, created_at) VALUES (gen_random_uuid(), (SELECT id FROM products WHERE slug = 'dich-vu-in-kl-3d-gia-cong-titan'), 'Thanh bar bán hám', 'Cái', 1200000, NULL, true, NOW());
INSERT INTO blog_posts (id, title_vi, slug, excerpt_vi, content_vi, category, tags, status, published_at, seo_title, seo_description, view_count, ai_generated, created_at, updated_at) VALUES (gen_random_uuid(), 'Dịch vụ in kl 3D gia công Titan — Thanh bar bán hám', 'dich-vu-in-kl-3d-gia-cong-titan-thanh-bar-ban-ham', 'Thanh bar bán hám thuộc dòng Dịch vụ in kl 3D gia công Titan của Alpha Digital Center. Giá tham khảo: 1.200.000 VND/Cái.', '## Thanh bar bán hám — chi tiết dịch vụ

**Thanh bar bán hám** là một biến thể thuộc dòng sản phẩm/dịch vụ **Dịch vụ in kl 3D gia công Titan** do Alpha Digital Center gia công. Biến thể này phù hợp với các yêu cầu gia công đặc thù trong phòng lab nha khoa hiện đại.

### Thông số kỹ thuật

- **Vật liệu:** Titan
- **Đơn vị tính:** Cái
- **Giá tham khảo:** 1.200.000 VND / Cái

### Quy trình gia công tại Alpha Digital Center

Mỗi biến thể gia công tại ADC đều trải qua quy trình khép kín, đảm bảo chất lượng ổn định và thời gian giao đúng hẹn:

1. **Tiếp nhận file & kiểm tra** — đội QC kiểm tra file CAD/CAM do labo gửi về, báo cáo sai sót nếu có.
2. **Thiết kế/điều chỉnh** (nếu thuê) — các chuyên viên thiết kế của ADC hiệu chỉnh theo vật liệu và yêu cầu lâm sàng.
3. **Gia công chính xác** — hệ thống máy CNC 5 trục, in 3D kim loại SLM, scanner E4 đảm bảo dung sai tối thiểu.
4. **QC xuất xưởng** — 5 vòng kiểm tra trước khi đóng gói, kèm phiếu gia công ghi rõ lô vật liệu.

### Ứng dụng lâm sàng

Thanh bar bán hám thường được chỉ định cho các case phục hình có yêu cầu độ chính xác cao và tính thẩm mỹ tự nhiên. Labo đối tác của Alpha Digital Center có thể đặt số lượng lớn với lead time ổn định.

### Liên hệ đặt hàng

Xem thêm các biến thể khác trong dòng [Dịch vụ in kl 3D gia công Titan](/san-pham/dich-vu-in-kl-3d-gia-cong-titan) hoặc [liên hệ trực tiếp](/lien-he) để nhận báo giá chi tiết cho số lượng lớn và lịch giao hàng.', 'san-pham', ARRAY['Titan','Thanh bar bán hám']::text[], 'published', NOW(), 'Dịch vụ in kl 3D gia công Titan — Thanh bar bán hám | Giá 1.200.000 VND — Alpha Digital Center', 'Thanh bar bán hám thuộc dòng Dịch vụ in kl 3D gia công Titan của Alpha Digital Center. Giá tham khảo: 1.200.000 VND/Cái. Bảo hành minh bạch, giao hàng đúng hẹn', 0, false, NOW(), NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO product_variants (id, product_id, variant_name_vi, unit, price_vnd, price_note, is_active, created_at) VALUES (gen_random_uuid(), (SELECT id FROM products WHERE slug = 'dich-vu-in-kl-3d-gia-cong-titan'), 'Thanh bar toàn hàm', 'Cái', 1600000, NULL, true, NOW());
INSERT INTO blog_posts (id, title_vi, slug, excerpt_vi, content_vi, category, tags, status, published_at, seo_title, seo_description, view_count, ai_generated, created_at, updated_at) VALUES (gen_random_uuid(), 'Dịch vụ in kl 3D gia công Titan — Thanh bar toàn hàm', 'dich-vu-in-kl-3d-gia-cong-titan-thanh-bar-toan-ham', 'Thanh bar toàn hàm thuộc dòng Dịch vụ in kl 3D gia công Titan của Alpha Digital Center. Giá tham khảo: 1.600.000 VND/Cái.', '## Thanh bar toàn hàm — chi tiết dịch vụ

**Thanh bar toàn hàm** là một biến thể thuộc dòng sản phẩm/dịch vụ **Dịch vụ in kl 3D gia công Titan** do Alpha Digital Center gia công. Biến thể này phù hợp với các yêu cầu gia công đặc thù trong phòng lab nha khoa hiện đại.

### Thông số kỹ thuật

- **Vật liệu:** Titan
- **Đơn vị tính:** Cái
- **Giá tham khảo:** 1.600.000 VND / Cái

### Quy trình gia công tại Alpha Digital Center

Mỗi biến thể gia công tại ADC đều trải qua quy trình khép kín, đảm bảo chất lượng ổn định và thời gian giao đúng hẹn:

1. **Tiếp nhận file & kiểm tra** — đội QC kiểm tra file CAD/CAM do labo gửi về, báo cáo sai sót nếu có.
2. **Thiết kế/điều chỉnh** (nếu thuê) — các chuyên viên thiết kế của ADC hiệu chỉnh theo vật liệu và yêu cầu lâm sàng.
3. **Gia công chính xác** — hệ thống máy CNC 5 trục, in 3D kim loại SLM, scanner E4 đảm bảo dung sai tối thiểu.
4. **QC xuất xưởng** — 5 vòng kiểm tra trước khi đóng gói, kèm phiếu gia công ghi rõ lô vật liệu.

### Ứng dụng lâm sàng

Thanh bar toàn hàm thường được chỉ định cho các case phục hình có yêu cầu độ chính xác cao và tính thẩm mỹ tự nhiên. Labo đối tác của Alpha Digital Center có thể đặt số lượng lớn với lead time ổn định.

### Liên hệ đặt hàng

Xem thêm các biến thể khác trong dòng [Dịch vụ in kl 3D gia công Titan](/san-pham/dich-vu-in-kl-3d-gia-cong-titan) hoặc [liên hệ trực tiếp](/lien-he) để nhận báo giá chi tiết cho số lượng lớn và lịch giao hàng.', 'san-pham', ARRAY['Titan','Thanh bar toàn hàm']::text[], 'published', NOW(), 'Dịch vụ in kl 3D gia công Titan — Thanh bar toàn hàm | Giá 1.600.000 VND — Alpha Digital Center', 'Thanh bar toàn hàm thuộc dòng Dịch vụ in kl 3D gia công Titan của Alpha Digital Center. Giá tham khảo: 1.600.000 VND/Cái. Bảo hành minh bạch, giao hàng đúng hẹn', 0, false, NOW(), NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO product_variants (id, product_id, variant_name_vi, unit, price_vnd, price_note, is_active, created_at) VALUES (gen_random_uuid(), (SELECT id FROM products WHERE slug = 'dich-vu-in-kl-3d-gia-cong-titan'), 'Thimble bán hàm', 'Cái', 1600000, NULL, true, NOW());
INSERT INTO blog_posts (id, title_vi, slug, excerpt_vi, content_vi, category, tags, status, published_at, seo_title, seo_description, view_count, ai_generated, created_at, updated_at) VALUES (gen_random_uuid(), 'Dịch vụ in kl 3D gia công Titan — Thimble bán hàm', 'dich-vu-in-kl-3d-gia-cong-titan-thimble-ban-ham', 'Thimble bán hàm thuộc dòng Dịch vụ in kl 3D gia công Titan của Alpha Digital Center. Giá tham khảo: 1.600.000 VND/Cái.', '## Thimble bán hàm — chi tiết dịch vụ

**Thimble bán hàm** là một biến thể thuộc dòng sản phẩm/dịch vụ **Dịch vụ in kl 3D gia công Titan** do Alpha Digital Center gia công. Biến thể này phù hợp với các yêu cầu gia công đặc thù trong phòng lab nha khoa hiện đại.

### Thông số kỹ thuật

- **Vật liệu:** Titan
- **Đơn vị tính:** Cái
- **Giá tham khảo:** 1.600.000 VND / Cái

### Quy trình gia công tại Alpha Digital Center

Mỗi biến thể gia công tại ADC đều trải qua quy trình khép kín, đảm bảo chất lượng ổn định và thời gian giao đúng hẹn:

1. **Tiếp nhận file & kiểm tra** — đội QC kiểm tra file CAD/CAM do labo gửi về, báo cáo sai sót nếu có.
2. **Thiết kế/điều chỉnh** (nếu thuê) — các chuyên viên thiết kế của ADC hiệu chỉnh theo vật liệu và yêu cầu lâm sàng.
3. **Gia công chính xác** — hệ thống máy CNC 5 trục, in 3D kim loại SLM, scanner E4 đảm bảo dung sai tối thiểu.
4. **QC xuất xưởng** — 5 vòng kiểm tra trước khi đóng gói, kèm phiếu gia công ghi rõ lô vật liệu.

### Ứng dụng lâm sàng

Thimble bán hàm thường được chỉ định cho các case phục hình có yêu cầu độ chính xác cao và tính thẩm mỹ tự nhiên. Labo đối tác của Alpha Digital Center có thể đặt số lượng lớn với lead time ổn định.

### Liên hệ đặt hàng

Xem thêm các biến thể khác trong dòng [Dịch vụ in kl 3D gia công Titan](/san-pham/dich-vu-in-kl-3d-gia-cong-titan) hoặc [liên hệ trực tiếp](/lien-he) để nhận báo giá chi tiết cho số lượng lớn và lịch giao hàng.', 'san-pham', ARRAY['Titan','Thimble bán hàm']::text[], 'published', NOW(), 'Dịch vụ in kl 3D gia công Titan — Thimble bán hàm | Giá 1.600.000 VND — Alpha Digital Center', 'Thimble bán hàm thuộc dòng Dịch vụ in kl 3D gia công Titan của Alpha Digital Center. Giá tham khảo: 1.600.000 VND/Cái. Bảo hành minh bạch, giao hàng đúng hẹn từ', 0, false, NOW(), NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO product_variants (id, product_id, variant_name_vi, unit, price_vnd, price_note, is_active, created_at) VALUES (gen_random_uuid(), (SELECT id FROM products WHERE slug = 'dich-vu-in-kl-3d-gia-cong-titan'), 'Thimble toàn hàm', 'Cái', 2400000, NULL, true, NOW());
INSERT INTO blog_posts (id, title_vi, slug, excerpt_vi, content_vi, category, tags, status, published_at, seo_title, seo_description, view_count, ai_generated, created_at, updated_at) VALUES (gen_random_uuid(), 'Dịch vụ in kl 3D gia công Titan — Thimble toàn hàm', 'dich-vu-in-kl-3d-gia-cong-titan-thimble-toan-ham', 'Thimble toàn hàm thuộc dòng Dịch vụ in kl 3D gia công Titan của Alpha Digital Center. Giá tham khảo: 2.400.000 VND/Cái.', '## Thimble toàn hàm — chi tiết dịch vụ

**Thimble toàn hàm** là một biến thể thuộc dòng sản phẩm/dịch vụ **Dịch vụ in kl 3D gia công Titan** do Alpha Digital Center gia công. Biến thể này phù hợp với các yêu cầu gia công đặc thù trong phòng lab nha khoa hiện đại.

### Thông số kỹ thuật

- **Vật liệu:** Titan
- **Đơn vị tính:** Cái
- **Giá tham khảo:** 2.400.000 VND / Cái

### Quy trình gia công tại Alpha Digital Center

Mỗi biến thể gia công tại ADC đều trải qua quy trình khép kín, đảm bảo chất lượng ổn định và thời gian giao đúng hẹn:

1. **Tiếp nhận file & kiểm tra** — đội QC kiểm tra file CAD/CAM do labo gửi về, báo cáo sai sót nếu có.
2. **Thiết kế/điều chỉnh** (nếu thuê) — các chuyên viên thiết kế của ADC hiệu chỉnh theo vật liệu và yêu cầu lâm sàng.
3. **Gia công chính xác** — hệ thống máy CNC 5 trục, in 3D kim loại SLM, scanner E4 đảm bảo dung sai tối thiểu.
4. **QC xuất xưởng** — 5 vòng kiểm tra trước khi đóng gói, kèm phiếu gia công ghi rõ lô vật liệu.

### Ứng dụng lâm sàng

Thimble toàn hàm thường được chỉ định cho các case phục hình có yêu cầu độ chính xác cao và tính thẩm mỹ tự nhiên. Labo đối tác của Alpha Digital Center có thể đặt số lượng lớn với lead time ổn định.

### Liên hệ đặt hàng

Xem thêm các biến thể khác trong dòng [Dịch vụ in kl 3D gia công Titan](/san-pham/dich-vu-in-kl-3d-gia-cong-titan) hoặc [liên hệ trực tiếp](/lien-he) để nhận báo giá chi tiết cho số lượng lớn và lịch giao hàng.', 'san-pham', ARRAY['Titan','Thimble toàn hàm']::text[], 'published', NOW(), 'Dịch vụ in kl 3D gia công Titan — Thimble toàn hàm | Giá 2.400.000 VND — Alpha Digital Center', 'Thimble toàn hàm thuộc dòng Dịch vụ in kl 3D gia công Titan của Alpha Digital Center. Giá tham khảo: 2.400.000 VND/Cái. Bảo hành minh bạch, giao hàng đúng hẹn t', 0, false, NOW(), NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO product_variants (id, product_id, variant_name_vi, unit, price_vnd, price_note, is_active, created_at) VALUES (gen_random_uuid(), (SELECT id FROM products WHERE slug = 'dich-vu-in-kl-3d-gia-cong-titan'), 'Máng HDPT', 'Cái', 2500000, NULL, true, NOW());
INSERT INTO blog_posts (id, title_vi, slug, excerpt_vi, content_vi, category, tags, status, published_at, seo_title, seo_description, view_count, ai_generated, created_at, updated_at) VALUES (gen_random_uuid(), 'Dịch vụ in kl 3D gia công Titan — Máng HDPT', 'dich-vu-in-kl-3d-gia-cong-titan-mang-hdpt', 'Máng HDPT thuộc dòng Dịch vụ in kl 3D gia công Titan của Alpha Digital Center. Giá tham khảo: 2.500.000 VND/Cái.', '## Máng HDPT — chi tiết dịch vụ

**Máng HDPT** là một biến thể thuộc dòng sản phẩm/dịch vụ **Dịch vụ in kl 3D gia công Titan** do Alpha Digital Center gia công. Biến thể này phù hợp với các yêu cầu gia công đặc thù trong phòng lab nha khoa hiện đại.

### Thông số kỹ thuật

- **Vật liệu:** Titan
- **Đơn vị tính:** Cái
- **Giá tham khảo:** 2.500.000 VND / Cái

### Quy trình gia công tại Alpha Digital Center

Mỗi biến thể gia công tại ADC đều trải qua quy trình khép kín, đảm bảo chất lượng ổn định và thời gian giao đúng hẹn:

1. **Tiếp nhận file & kiểm tra** — đội QC kiểm tra file CAD/CAM do labo gửi về, báo cáo sai sót nếu có.
2. **Thiết kế/điều chỉnh** (nếu thuê) — các chuyên viên thiết kế của ADC hiệu chỉnh theo vật liệu và yêu cầu lâm sàng.
3. **Gia công chính xác** — hệ thống máy CNC 5 trục, in 3D kim loại SLM, scanner E4 đảm bảo dung sai tối thiểu.
4. **QC xuất xưởng** — 5 vòng kiểm tra trước khi đóng gói, kèm phiếu gia công ghi rõ lô vật liệu.

### Ứng dụng lâm sàng

Máng HDPT thường được chỉ định cho các case phục hình có yêu cầu độ chính xác cao và tính thẩm mỹ tự nhiên. Labo đối tác của Alpha Digital Center có thể đặt số lượng lớn với lead time ổn định.

### Liên hệ đặt hàng

Xem thêm các biến thể khác trong dòng [Dịch vụ in kl 3D gia công Titan](/san-pham/dich-vu-in-kl-3d-gia-cong-titan) hoặc [liên hệ trực tiếp](/lien-he) để nhận báo giá chi tiết cho số lượng lớn và lịch giao hàng.', 'san-pham', ARRAY['Titan','Máng HDPT']::text[], 'published', NOW(), 'Dịch vụ in kl 3D gia công Titan — Máng HDPT | Giá 2.500.000 VND — Alpha Digital Center', 'Máng HDPT thuộc dòng Dịch vụ in kl 3D gia công Titan của Alpha Digital Center. Giá tham khảo: 2.500.000 VND/Cái. Bảo hành minh bạch, giao hàng đúng hẹn từ ADC.', 0, false, NOW(), NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO product_variants (id, product_id, variant_name_vi, unit, price_vnd, price_note, is_active, created_at) VALUES (gen_random_uuid(), (SELECT id FROM products WHERE slug = 'dich-vu-in-kl-3d-gia-cong-titan'), 'Hàm khung', 'Cái', 500000, NULL, true, NOW());
INSERT INTO blog_posts (id, title_vi, slug, excerpt_vi, content_vi, category, tags, status, published_at, seo_title, seo_description, view_count, ai_generated, created_at, updated_at) VALUES (gen_random_uuid(), 'Dịch vụ in kl 3D gia công Titan — Hàm khung', 'dich-vu-in-kl-3d-gia-cong-titan-ham-khung', 'Hàm khung thuộc dòng Dịch vụ in kl 3D gia công Titan của Alpha Digital Center. Giá tham khảo: 500.000 VND/Cái.', '## Hàm khung — chi tiết dịch vụ

**Hàm khung** là một biến thể thuộc dòng sản phẩm/dịch vụ **Dịch vụ in kl 3D gia công Titan** do Alpha Digital Center gia công. Biến thể này phù hợp với các yêu cầu gia công đặc thù trong phòng lab nha khoa hiện đại.

### Thông số kỹ thuật

- **Vật liệu:** Titan
- **Đơn vị tính:** Cái
- **Giá tham khảo:** 500.000 VND / Cái

### Quy trình gia công tại Alpha Digital Center

Mỗi biến thể gia công tại ADC đều trải qua quy trình khép kín, đảm bảo chất lượng ổn định và thời gian giao đúng hẹn:

1. **Tiếp nhận file & kiểm tra** — đội QC kiểm tra file CAD/CAM do labo gửi về, báo cáo sai sót nếu có.
2. **Thiết kế/điều chỉnh** (nếu thuê) — các chuyên viên thiết kế của ADC hiệu chỉnh theo vật liệu và yêu cầu lâm sàng.
3. **Gia công chính xác** — hệ thống máy CNC 5 trục, in 3D kim loại SLM, scanner E4 đảm bảo dung sai tối thiểu.
4. **QC xuất xưởng** — 5 vòng kiểm tra trước khi đóng gói, kèm phiếu gia công ghi rõ lô vật liệu.

### Ứng dụng lâm sàng

Hàm khung thường được chỉ định cho các case phục hình có yêu cầu độ chính xác cao và tính thẩm mỹ tự nhiên. Labo đối tác của Alpha Digital Center có thể đặt số lượng lớn với lead time ổn định.

### Liên hệ đặt hàng

Xem thêm các biến thể khác trong dòng [Dịch vụ in kl 3D gia công Titan](/san-pham/dich-vu-in-kl-3d-gia-cong-titan) hoặc [liên hệ trực tiếp](/lien-he) để nhận báo giá chi tiết cho số lượng lớn và lịch giao hàng.', 'san-pham', ARRAY['Titan','Hàm khung']::text[], 'published', NOW(), 'Dịch vụ in kl 3D gia công Titan — Hàm khung | Giá 500.000 VND — Alpha Digital Center', 'Hàm khung thuộc dòng Dịch vụ in kl 3D gia công Titan của Alpha Digital Center. Giá tham khảo: 500.000 VND/Cái. Bảo hành minh bạch, giao hàng đúng hẹn từ ADC.', 0, false, NOW(), NOW()) ON CONFLICT (slug) DO NOTHING;

INSERT INTO product_variants (id, product_id, variant_name_vi, unit, price_vnd, price_note, is_active, created_at) VALUES (gen_random_uuid(), (SELECT id FROM products WHERE slug = 'dich-vu-gia-cong-them-in-3d-kim-loai'), 'In rỗng', 'Cái', 1000000, 'Gia công kĩ thuật cao trên mẫu in kim loại 3D', true, NOW());
INSERT INTO blog_posts (id, title_vi, slug, excerpt_vi, content_vi, category, tags, status, published_at, seo_title, seo_description, view_count, ai_generated, created_at, updated_at) VALUES (gen_random_uuid(), 'Dịch vụ gia công thêm in 3D Kim loại — In rỗng', 'dich-vu-gia-cong-them-in-3d-kim-loai-in-rong', 'In rỗng thuộc dòng Dịch vụ gia công thêm in 3D Kim loại của Alpha Digital Center. Giá tham khảo: 1.000.000 VND/Cái.', '## In rỗng — chi tiết dịch vụ

**In rỗng** là một biến thể thuộc dòng sản phẩm/dịch vụ **Dịch vụ gia công thêm in 3D Kim loại** do Alpha Digital Center gia công. Biến thể này phù hợp với các yêu cầu gia công đặc thù trong phòng lab nha khoa hiện đại.

### Thông số kỹ thuật

- **Đơn vị tính:** Cái
- **Giá tham khảo:** 1.000.000 VND / Cái

### Ghi chú từ nhà sản xuất

> Gia công kĩ thuật cao trên mẫu in kim loại 3D

### Quy trình gia công tại Alpha Digital Center

Mỗi biến thể gia công tại ADC đều trải qua quy trình khép kín, đảm bảo chất lượng ổn định và thời gian giao đúng hẹn:

1. **Tiếp nhận file & kiểm tra** — đội QC kiểm tra file CAD/CAM do labo gửi về, báo cáo sai sót nếu có.
2. **Thiết kế/điều chỉnh** (nếu thuê) — các chuyên viên thiết kế của ADC hiệu chỉnh theo vật liệu và yêu cầu lâm sàng.
3. **Gia công chính xác** — hệ thống máy CNC 5 trục, in 3D kim loại SLM, scanner E4 đảm bảo dung sai tối thiểu.
4. **QC xuất xưởng** — 5 vòng kiểm tra trước khi đóng gói, kèm phiếu gia công ghi rõ lô vật liệu.

### Ứng dụng lâm sàng

In rỗng thường được chỉ định cho các case phục hình có yêu cầu độ chính xác cao và tính thẩm mỹ tự nhiên. Labo đối tác của Alpha Digital Center có thể đặt số lượng lớn với lead time ổn định.

### Liên hệ đặt hàng

Xem thêm các biến thể khác trong dòng [Dịch vụ gia công thêm in 3D Kim loại](/san-pham/dich-vu-gia-cong-them-in-3d-kim-loai) hoặc [liên hệ trực tiếp](/lien-he) để nhận báo giá chi tiết cho số lượng lớn và lịch giao hàng.', 'san-pham', ARRAY['In rỗng']::text[], 'published', NOW(), 'Dịch vụ gia công thêm in 3D Kim loại — In rỗng | Giá 1.000.000 VND — Alpha Digital Center', 'In rỗng thuộc dòng Dịch vụ gia công thêm in 3D Kim loại của Alpha Digital Center. Giá tham khảo: 1.000.000 VND/Cái. Bảo hành minh bạch, giao hàng đúng hẹn từ AD', 0, false, NOW(), NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO product_variants (id, product_id, variant_name_vi, unit, price_vnd, price_note, is_active, created_at) VALUES (gen_random_uuid(), (SELECT id FROM products WHERE slug = 'dich-vu-gia-cong-them-in-3d-kim-loai'), 'Mill kết nối', 'Cái', 1000000, NULL, true, NOW());
INSERT INTO blog_posts (id, title_vi, slug, excerpt_vi, content_vi, category, tags, status, published_at, seo_title, seo_description, view_count, ai_generated, created_at, updated_at) VALUES (gen_random_uuid(), 'Dịch vụ gia công thêm in 3D Kim loại — Mill kết nối', 'dich-vu-gia-cong-them-in-3d-kim-loai-mill-ket-noi', 'Mill kết nối thuộc dòng Dịch vụ gia công thêm in 3D Kim loại của Alpha Digital Center. Giá tham khảo: 1.000.000 VND/Cái.', '## Mill kết nối — chi tiết dịch vụ

**Mill kết nối** là một biến thể thuộc dòng sản phẩm/dịch vụ **Dịch vụ gia công thêm in 3D Kim loại** do Alpha Digital Center gia công. Biến thể này phù hợp với các yêu cầu gia công đặc thù trong phòng lab nha khoa hiện đại.

### Thông số kỹ thuật

- **Đơn vị tính:** Cái
- **Giá tham khảo:** 1.000.000 VND / Cái

### Quy trình gia công tại Alpha Digital Center

Mỗi biến thể gia công tại ADC đều trải qua quy trình khép kín, đảm bảo chất lượng ổn định và thời gian giao đúng hẹn:

1. **Tiếp nhận file & kiểm tra** — đội QC kiểm tra file CAD/CAM do labo gửi về, báo cáo sai sót nếu có.
2. **Thiết kế/điều chỉnh** (nếu thuê) — các chuyên viên thiết kế của ADC hiệu chỉnh theo vật liệu và yêu cầu lâm sàng.
3. **Gia công chính xác** — hệ thống máy CNC 5 trục, in 3D kim loại SLM, scanner E4 đảm bảo dung sai tối thiểu.
4. **QC xuất xưởng** — 5 vòng kiểm tra trước khi đóng gói, kèm phiếu gia công ghi rõ lô vật liệu.

### Ứng dụng lâm sàng

Mill kết nối thường được chỉ định cho các case phục hình có yêu cầu độ chính xác cao và tính thẩm mỹ tự nhiên. Labo đối tác của Alpha Digital Center có thể đặt số lượng lớn với lead time ổn định.

### Liên hệ đặt hàng

Xem thêm các biến thể khác trong dòng [Dịch vụ gia công thêm in 3D Kim loại](/san-pham/dich-vu-gia-cong-them-in-3d-kim-loai) hoặc [liên hệ trực tiếp](/lien-he) để nhận báo giá chi tiết cho số lượng lớn và lịch giao hàng.', 'san-pham', ARRAY['Mill kết nối']::text[], 'published', NOW(), 'Dịch vụ gia công thêm in 3D Kim loại — Mill kết nối | Giá 1.000.000 VND — Alpha Digital Center', 'Mill kết nối thuộc dòng Dịch vụ gia công thêm in 3D Kim loại của Alpha Digital Center. Giá tham khảo: 1.000.000 VND/Cái. Bảo hành minh bạch, giao hàng đúng hẹn', 0, false, NOW(), NOW()) ON CONFLICT (slug) DO NOTHING;

COMMIT;

-- Summary counts
SELECT 'categories' AS t, count(*) FROM product_categories UNION ALL SELECT 'products', count(*) FROM products UNION ALL SELECT 'variants', count(*) FROM product_variants UNION ALL SELECT 'blog_posts_san_pham', count(*) FROM blog_posts WHERE category = 'san-pham';
